// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import PopupForm from '@/components/PopupForm'
// // import Navbar from "@/components/Navbar"
// import Footer from "@/components/Footer"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });  

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//       {/* <Navbar /> */}
//         {children}
//         <PopupForm />
//       <Footer />
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PopupForm from '@/components/PopupForm';
import PopupForm2 from '@/components/PopupForm2';

import Popup from '@/components/Popup';
import UserDataHandler from '@/components/UserDataHandler';
import Footer from "@/components/Footer";
// import Navbar from "@/components/Navbar";
import AuthProvider from '@/components/AuthProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});  

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* <Navbar /> */}
          
          <UserDataHandler />

          {children}
          <PopupForm2 />
          <PopupForm />
          <Popup />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}